export const SliderData = [
  {
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/71NUwTzSnjL.__AC_SX300_SY300_QL70_ML2_.jpg",
  },
  {
    image:
      "https://images-na.ssl-images-amazon.com/images/I/818-F8luJqL._AC_SL1250_.jpg",
  },
  {
    image:
      "https://sm.ign.com/t/ign_za/gallery/s/spider-man/spider-man-far-from-home-official-movie-posters_ex7e.1080.jpg",
  },
  {
    image:
      "https://images-na.ssl-images-amazon.com/images/I/715Hu0k189L._AC_SY879_.jpg",
  },
  {
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/91bHRU1T0VL.__AC_SX300_SY300_QL70_ML2_.jpg",
  },
];
